# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FireStoreDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FireStoreDemo
  pod 'FireBase/Core'
  pod 'FireBase/Firestore'
  pod 'Firebase/Auth'		
  target 'FireStoreDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FireStoreDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
